stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - artifacts/raw/
    